name: Build release target
on: [push]
jobs:
  build-release:
    container:
      image: unknown
    runs-on: [ self-hosted, builder ]
    steps:
      - run: echo "ðŸŽ‰  The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout branch ${{ github.ref }} of repository ${{ github.repository }}."
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Build release
        run: cd software && ./cmake_build_release.sh
